name: CI
on:
  push:
  pull_request:
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Try building
          run: |
            echo "note: texinfo contains makeinfo"
            sudo apt-get install texinfo bison flex
            chmod +x mingw-w64-build
            ./mingw-w64-build x86_64
        - name: directories
          run: |
            ls
            echo "todo: expand"
  build-i686:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Try building
          run: |
            echo "note: texinfo contains makeinfo"
            sudo apt-get install texinfo bison flex
            chmod +x mingw-w64-build
            ./mingw-w64-build i686
        - name: directories
          run: |
            ls
            echo "todo: expand"
# build-both: