name: CI
on:
  push:
  pull_request:
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Try building
          run: |
            echo "note: texinfo contains makeinfo"
            sudo apt-get install texinfo bison flex
            chmod +x mingw-w64-build
            ./mingw-w64-build x86_64
        - uses: actions/upload-artifact@v1
          with:
            name: x86_64-pc-linux-gnu-x86_64-w64-mingw64
            path: x86_64-w64-mingw32/
  build-i686:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Try building
          run: |
            echo "note: texinfo contains makeinfo"
            sudo apt-get install texinfo bison flex
            chmod +x mingw-w64-build
            ./mingw-w64-build i686
        - uses: actions/upload-artifact@v1
          with:
            name: x86_64-pc-linux-gnu-i686-w64-mingw64
            path: i686-w64-mingw32/
# build-both: